# --- General options --- #

# Name of website
title: Tonia's Tkachuk Portfolio

# Short description of my site
description: I use the latest technologies to create Android apps and websites. I find each project to be unique and enjoy making useful stuff work. In my free time, I like to read or play with my son.

avatar: "/img/tonia_tkachuk_profile.jpg"
